# Generated by Django 3.2.10 on 2022-02-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='Task_tittle',
        ),
    ]
